### ISSUE TITLE
escaped newlines not recognized properly

### ISSUE THREAD

**Issue by LoisDuplain** [42School/norminette#104]
**Describe the bug**
You just have to look...
[Screenshot](https://cdn.discordapp.com/attachments/780794552335335465/824231342169915402/Screen_Shot_2021-03-24_at_11.40.49_AM.png)
The norminette say: OK
The old norminette say: NOT OK

There are more than 25 lines, and lines are more than 80 characters long..

**Comment by N0ich** [comment]
Hello,
This is an issue system for the new norminette. this is not the place to complain about it.
I will fix your issue, but i'd appreciate a bit more details (as suggested in the issue default format), as well as a clearer title regarding to what seems to be the issue.
Regardless, this is an important issue that will be fixed in the next release.
