### ISSUE TITLE
Struct alignment rule not applying

### ISSUE THREAD

**Issue by csphilli** [42School/norminette#106]
**Describe the bug**
As title says, the below is not being flagged for alignment issue.

**Erroneous code**
```
typedef struct s_list
{
	t_node			*head;
	t_node			*tail;
	t_node			*cur;
}t_list;
```

To add to this, tabs between _struct_ and the _s_name_ are not allowed which can/will cause a cascading alignment issue with the overall _t_name_

python3 --version : 3.9.2
macOS Catalina: 10.15.7

**Comment by N0ich** [comment]
Hello,
Thank you for your issue.
There are a few things here: 
- `tabs between struct and the s_name are not allowed`: This is intended, since the type is `struct s_list` and adding tabs would create inconsistency. 
- The indent seems fine here. Besides the `}t_list;` which could be better, there is no error. Each variable is aligned in its scope (so variable declared within the struct are not expected to be aligned with the struct itself).
Which line is creating the error according to you? 
I will check the pdf to make sure everything is properly explained as it changes a bit from what was expected in the previous norminette.
