### ISSUE TITLE
Multiple errors with function pointer declaration

### ISSUE THREAD

**Issue by D4ryl00** [42School/norminette#35]
The lines 96-97 contain my function pointer declaration:
![image](https://user-images.githubusercontent.com/13605410/106220446-d1c4cd80-61db-11eb-9055-3ef1924af702.png)

These are encounter errors:
![image](https://user-images.githubusercontent.com/13605410/106220587-21a39480-61dc-11eb-8f54-942bea0b3b57.png)

Thanks

**Comment by N0ich** [comment]
Hello and thank you for reporting this

Could you integrate the code itself instead of screenshots?

**Comment by D4ryl00** [comment]
Sure :)
``` c
void	test(void)
{
	int	i;
	int	(*f)(const t_module *m, char ***p_options);

	(void)i;
	(void)f;
}
```

**Comment by vincentvis** [comment]
It seems like it's not recognized as a variable definition?
If you put a newline between int i and the function pointer it says OK.
Apart from that it wants a space between * and m, but that's another bug which I thought was fixed with [21](https://github.com/42School/norminette/issues/21), [18](https://github.com/42School/norminette/issues/18), [16](https://github.com/42School/norminette/issues/16), [14](https://github.com/42School/norminette/issues/14), but maybe not for this scope ;-)

```
void	test(void)
{
	int	i;
	int	x;

	int (*f)(const t_module * m, char ***p_options);
	(void)i;
	(void)f;
}
```

If it's not a custom typedef it only works without space

```
void	test(void)
{
	int	i;
	int	x;

	int (*f)(const int *m, char ***p_options);
	(void)i;
	(void)f;
}
```
