### ISSUE TITLE
Not recognizing syntax it should be able to recognize AND issuing a incomprehensible error message upon failure to recognize it.

### ISSUE THREAD

**Issue by Vinni-Cedraz** [42School/norminette#411]
Not recognizing syntax it should be able to recognize AND issuing a incomprehensible error message upon failure to recognize it.

**Erroneous code**
```
getter_stdio()->input = dup2_and_close(bkp_fd, STDIN_FILENO);
```

**Additional infos**
 - OS: ubuntu 20.04
 - python --version: Python 2.7.18
 - norminette -v: norminette 3.3.53

**Additional context**

Here is the supposed error norminette found in the code, notice how bizarre imprecise the error message is:

![Screenshot from 2023-07-18 14-24-27](https://github.com/42School/norminette/assets/92558763/bc2b9150-7784-4046-88b7-80275bbb04d9)

**Comment by NiumXp** [comment]
Hello, @Vinni-Cedraz!

The error is because `IsFunctionCall` does not work proper with the `,` in the assignment value. Here is a minimal code to reproduce your error:
```c
void    main(void)
{
    x() = z(1, 2);
}
```
> It not occurs only with comma, if you change it to `&&` or `||`, we will get the same error.

Btw, if you try to call `z` with only one argument, it will works. So you can do it as a temporary solution or move it to a variable.
